---
name: Vulnerability Scan

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  vulnerability-scan:
    name: üõ°Ô∏è Vulnerability Scan (üç® ${{ matrix.flavor }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["cpp", "rust"]
    permissions:
      security-events: write # is needed by github/codeql-action/upload-sarif to upload sarif files
    steps:
      - uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - uses: crazy-max/ghaction-container-scan@4d8e0acba576e46016cbd65b9ecfc604e85e3990 # v3.2.0
        id: scan
        with:
          image: ghcr.io/${{ github.repository }}-${{ matrix.flavor }}:latest
          dockerfile: .devcontainer/Dockerfile
      - uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        if: steps.scan.outputs.sarif != ''
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
