---
name: Vulnerability Scan

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  vulnerability-scan:
    name: üõ°Ô∏è Vulnerability Scan (üç® ${{ matrix.flavor }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["cpp", "rust"]
    permissions:
      security-events: write # is needed by github/codeql-action/upload-sarif to upload sarif files
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - uses: crazy-max/ghaction-container-scan@4d8e0acba576e46016cbd65b9ecfc604e85e3990 # v3.2.0
        id: scan
        with:
          image: ghcr.io/${{ github.repository }}-${{ matrix.flavor }}:latest
          dockerfile: .devcontainer/Dockerfile
      - uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
        if: steps.scan.outputs.sarif != ''
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
