---
name: Document Generation

on:
  workflow_call:

permissions: {}

jobs:
  generate-documents:
    name: Generate Documents
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          set -Eeuo pipefail
          sudo apt-get update && sudo apt-get install --no-install-recommends -y plantuml
          python -m pip install gherkin-official==35.1.0 sbdl==1.16.4
      - name: Generate SRS document
        run: |
          set -Eeuo pipefail
          python docs/support/gherkin-to-sbdl.py test/cpp/features/*.feature
          sbdl -m template-fill --template docs/templates/software-requirements-specification.md.j2 output.sbdl > software-requirements-specification.md
      - uses: docker://pandoc/extra:3.7.0@sha256:a703d335fa237f8fc3303329d87e2555dca5187930da38bfa9010fa4e690933a
        with:
          args: --template eisvogel --listings --number-sections --output software-requirements-specification.pdf software-requirements-specification.md
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: documents
          path: "*.pdf"
          retention-days: 2
